version: '3.2'

services:
  db:
    image: mysql:5.7.22
    command: mysqld --character-set-server=utf8mb4
    restart: always
    container_name: express-local-db
    hostname: express-local-db
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    restart: always
    container_name: express-local-db-adminer
    ports:
      - 8081:8080